version: '3'
services:
  cloudcompy:
    build:
      context: .
      dockerfile: Dockerfile
    image: saintpm/cloudcompy:v1.0
    container_name: cloudcompy
    volumes:
      # - ~/CloudComPy/test:/root/CloudComPy
      - ./notebooks:/app/cloudcompy/notebooks
    entrypoint: /bin/bash -c /entrypoint.sh && jupyter notebook --ip 0.0.0.0 --port 8889 --allow-root --no-browser --notebook-dir=/app/cloudcompy/notebooks
    # command: jupyter notebook --ip 0.0.0.0 --port 8889 --allow-root --no-browser --notebook-dir=/app/notebooks
    ports:
      - "8888:8888"
      - "8889:8889"
