version: '3'
services:
  cloudcompy:
    build:
      context: .
      dockerfile: Dockerfile
    image: cloudcompy:1.0
    container_name: cloudcompy
    volumes:
      - ~/CloudComPy/test:/root/CloudComPy
      - ./notebooks:/app/notebooks
    entrypoint: /bin/bash
    # command: jupyter notebook --ip 0.0.0.0 --port 8889 --allow-root --no-browser --notebook-dir=/app/notebooks
    ports:
      - "8888:8888" 
