name: Clone Repository

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v2

    - name: Clone external repository
      run: |
        git clone --recursive https://github.com/CloudCompare/CloudCompare

    - name: Commit and push changes
      run: |
        git config --global user.name 'Peter Mwendia'
        git config --global user.email 'ptermwendia@gmail.com'
        git add .
        git commit -m "Add CloudCompare repository"
        git push
